<?xml version="1.0" encoding="UTF-8" ?>
<testsuite failures="0" time="1.761" errors="5" skipped="0" tests="5" name="org.eclipse.moquette.server.ServerIntegrationFuseTest">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/home/archer/bin/jdk1.7.0_45/jre/lib/i386"/>
    <property name="java.vm.version" value="24.45-b08"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/archer/Documents/mqtt/src/moquette/broker"/>
    <property name="java.runtime.version" value="1.7.0_45-b18"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/home/archer/bin/jdk1.7.0_45/jre/lib/endorsed"/>
    <property name="os.arch" value="i386"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/i386:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="51.0"/>
    <property name="sun.management.compiler" value="HotSpot Tiered Compilers"/>
    <property name="os.version" value="3.13.0-37-generic"/>
    <property name="user.home" value="/home/archer"/>
    <property name="user.timezone" value="America/New_York"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.7"/>
    <property name="user.name" value="archer"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="1.7"/>
    <property name="sun.arch.data.model" value="32"/>
    <property name="java.home" value="/home/archer/bin/jdk1.7.0_45/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean package"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.7.0_45"/>
    <property name="java.ext.dirs" value="/home/archer/bin/jdk1.7.0_45/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/home/archer/bin/jdk1.7.0_45/jre/lib/resources.jar:/home/archer/bin/jdk1.7.0_45/jre/lib/rt.jar:/home/archer/bin/jdk1.7.0_45/jre/lib/sunrsasign.jar:/home/archer/bin/jdk1.7.0_45/jre/lib/jsse.jar:/home/archer/bin/jdk1.7.0_45/jre/lib/jce.jar:/home/archer/bin/jdk1.7.0_45/jre/lib/charsets.jar:/home/archer/bin/jdk1.7.0_45/jre/lib/jfr.jar:/home/archer/bin/jdk1.7.0_45/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase time="0.188" classname="org.eclipse.moquette.server.ServerIntegrationFuseTest" name="checkWillTestmaentIsPublishedOnConnectionKill_noRetain">
    <error message="Address already in use" type="java.net.BindException">java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:101)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:478)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.bind(DefaultChannelPipeline.java:1000)
	at io.netty.channel.DefaultChannelHandlerContext.invokeBind(DefaultChannelHandlerContext.java:451)
	at io.netty.channel.DefaultChannelHandlerContext.bind(DefaultChannelHandlerContext.java:436)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:842)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:193)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:744)
</error>
    <system-out>Server stopping...
Server stopped
</system-out>
  </testcase>
  <testcase time="0.384" classname="org.eclipse.moquette.server.ServerIntegrationFuseTest" name="checkReplayStoredPublish_forNoCleanSession_qos1">
    <error message="Address already in use" type="java.net.BindException">java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:101)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:478)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.bind(DefaultChannelPipeline.java:1000)
	at io.netty.channel.DefaultChannelHandlerContext.invokeBind(DefaultChannelHandlerContext.java:451)
	at io.netty.channel.DefaultChannelHandlerContext.bind(DefaultChannelHandlerContext.java:436)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:842)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:193)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:744)
</error>
    <system-out>Server stopping...
Server stopped
</system-out>
  </testcase>
  <testcase time="0.367" classname="org.eclipse.moquette.server.ServerIntegrationFuseTest" name="checkQoS2SuscriberDisconnectReceivePersistedPublishes">
    <error message="Address already in use" type="java.net.BindException">java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:101)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:478)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.bind(DefaultChannelPipeline.java:1000)
	at io.netty.channel.DefaultChannelHandlerContext.invokeBind(DefaultChannelHandlerContext.java:451)
	at io.netty.channel.DefaultChannelHandlerContext.bind(DefaultChannelHandlerContext.java:436)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:842)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:193)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:744)
</error>
    <system-out>Server stopping...
Server stopped
</system-out>
  </testcase>
  <testcase time="0.378" classname="org.eclipse.moquette.server.ServerIntegrationFuseTest" name="checkReplayofStoredPublishResumeAfter_a_disconnect_cleanSessionFalseQoS1">
    <error message="Address already in use" type="java.net.BindException">java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:101)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:478)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.bind(DefaultChannelPipeline.java:1000)
	at io.netty.channel.DefaultChannelHandlerContext.invokeBind(DefaultChannelHandlerContext.java:451)
	at io.netty.channel.DefaultChannelHandlerContext.bind(DefaultChannelHandlerContext.java:436)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:842)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:193)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:744)
</error>
    <system-out>Server stopping...
Server stopped
</system-out>
  </testcase>
  <testcase time="0.442" classname="org.eclipse.moquette.server.ServerIntegrationFuseTest" name="connectWithCredentials">
    <error message="Address already in use" type="java.net.BindException">java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:101)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:478)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.bind(DefaultChannelPipeline.java:1000)
	at io.netty.channel.DefaultChannelHandlerContext.invokeBind(DefaultChannelHandlerContext.java:451)
	at io.netty.channel.DefaultChannelHandlerContext.bind(DefaultChannelHandlerContext.java:436)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:842)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:193)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:321)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:744)
</error>
    <system-out>Server stopping...
Server stopped
</system-out>
    <system-err>Oct 27, 2014 4:18:24 AM com.lmax.disruptor.FatalExceptionHandler handleEventException
SEVERE: Exception processing: 1 org.eclipse.moquette.spi.impl.ValueEvent@1321838
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:155)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:50)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
	... 6 more
Caused by: java.lang.IllegalAccessError: DB has been closed
	at org.mapdb.EngineWrapper.checkClosed(EngineWrapper.java:161)
	at org.mapdb.Caches$HashTable.get(Caches.java:325)
	at org.mapdb.HTreeMap.putInner(HTreeMap.java:496)
	at org.mapdb.HTreeMap.put(HTreeMap.java:484)
	at org.eclipse.moquette.spi.persistence.MapDBPersistentStore.updateSubscriptions(MapDBPersistentStore.java:208)
	at org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore.activate(SubscriptionsStore.java:188)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnect(ProtocolProcessor.java:213)
	... 10 more

Exception in thread &quot;pool-27-thread-1&quot; java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:45)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:147)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:155)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:50)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
	... 6 more
Caused by: java.lang.IllegalAccessError: DB has been closed
	at org.mapdb.EngineWrapper.checkClosed(EngineWrapper.java:161)
	at org.mapdb.Caches$HashTable.get(Caches.java:325)
	at org.mapdb.HTreeMap.putInner(HTreeMap.java:496)
	at org.mapdb.HTreeMap.put(HTreeMap.java:484)
	at org.eclipse.moquette.spi.persistence.MapDBPersistentStore.updateSubscriptions(MapDBPersistentStore.java:208)
	at org.eclipse.moquette.spi.impl.subscriptions.SubscriptionsStore.activate(SubscriptionsStore.java:188)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.processConnect(ProtocolProcessor.java:213)
	... 10 more
</system-err>
  </testcase>
</testsuite>